### PR TITLE
fix: add needed params in the docker composer file to activate batch pool delisting

### PR DESCRIPTION
**Pull request by ginnun**
This change will activate batch delisting of stake pools from the smash server.

# Context

The batch delisting job was not kicking in.

# Proposed Solution

# Important Changes Introduced

### CODE REVIEW

**Review by iccicci — DISMISSED** [review]
LGTM!

**Review by pczeglik-iohk — DISMISSED** [review]

**Review by AngelCastilloB — APPROVED** [review]
LGTM

**Review by mirceahasegan — APPROVED** [review]
LGTM

**Review by iccicci — APPROVED** [review]
Great code replication cleanup

**Pull request merged**
