### PR TITLE
refactor(core): update cardano serialization lib to 11.0.5

### PR DESCRIPTION
**Pull request by jmagan**
# Context

The package core had a dependency with Cardano Serialization Lib 11.0.0-rc.6. This version is a release candidate and it had some bugs, which were afterwards fixed. I updated and run the tests for version 11.0.5 and all tests passed successfully. Maybe this change must be deeply reviewed, because it can affect to many packages and I don't know the whole picture of this project.

# Proposed Solution

# Important Changes Introduced

### CODE REVIEW

**Review by mkazlauskas — CHANGES_REQUESTED** [review]
Please update commit type to `refactor`. Looks good otherwise!

**Comment by jmagan** [comment]
Done!

**Comment by mkazlauskas** [comment]
Thanks @jmagan, but I meant git commit message :sweat_smile: It's used for generating the CHANGELOG's

**Comment by jmagan** [comment]
hehe, okey. then, do I need resend the PR? Or is there some way to change on Github?

**Comment by mkazlauskas** [comment]
You can just amend the message locally (`git commit --amend` should do it in this case) and `git push --force` to this branch

**Comment by jmagan** [comment]
cool, I though amend was only for offline changes :) I think now it's correct

**Review by mkazlauskas — APPROVED** [review]
Thanks again!

**Review by rhyslbw — APPROVED** [review]

**Pull request merged**
