### PR TITLE
LW 11029: Refactor block body projection for cbor inclusion

### PR DESCRIPTION
**Pull request by will-break-it**
# Context

[LW-11029](https://input-output.atlassian.net/browse/LW-11029)

# Proposed Solution

# Important Changes Introduced

[LW-11029]: https://input-output.atlassian.net/browse/LW-11029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mkazlauskas — APPROVED** [review]
Nice work! :rocket:

**Review by ginnun — APPROVED** [review]
lgtm

**Review by mirceahasegan — APPROVED** [review]
lgtm. How is performance compared to mapping transaction fields?

**Comment by will-break-it** [comment]
@mirceahasegan I've rerun projection on preprod until block 200k and it was faster.
current master branch impl took around ~50mins, and this one ~40mins.
(deleted all docker containers + volumes to prevent any caching)

**Pull request merged**
