### PR TITLE
build: bump yarn plugin nixify

### PR DESCRIPTION
**Pull request by iccicci**
# Context

Current version of `yarn-plugin-nixify` generates a `yarn-project.nix` file with randomly sorted `cacheEntries`; this, too often, is source of merge conflicts in case of merge between two branches both impacting some `package.json` files.

# Proposed Solution

As per [this conversation](https://github.com/stephank/yarn-plugin-nixify/issues/46) I just run

```bash
yarn plugin import "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
yarn
```

and committed the result. As per my checks it seems everything is working as expected.

The new sorted `cacheEntries` should significantly reduce the probability of merge conflicts.

# Important Changes Introduced

An alphabetical sorted `cacheEntries` is not the only change introduced by the new version of the plugin: the `yarn-project.nix` file contains many other changes.

### CODE REVIEW

**Comment by rhyslbw** [comment]
@gytis-ivaskevicius would you mind verifying this change by reviewing the [additional changes](https://github.com/input-output-hk/cardano-js-sdk/pull/513/files#diff-6d359c8592cd08a5443a4ac76549b2283066c245d8b9d84e73ecb38414b4d660R4-R148) and ensuring it builds before we merge?

**Review by mkazlauskas — DISMISSED** [review]

**Comment by tshaynik** [comment]
I just added a commit to get `nix build` to work correctly, by overriding the installPhase of the `production-deps` derivation.
The default installPhase provided by yarn-plugin nixify recently got stricter in [which files it copies over](https://github.com/stephank/yarn-plugin-nixify/commit/d7620c8bd356032cfe2d20634c48ed7869177b80) to reduce package size, but we have our own optimizations in place already that more effectively reduce package size.

**Review by gytis-ivaskevicius — APPROVED** [review]
Thank you!!

**Review by gytis-ivaskevicius — APPROVED** [review]
Rebased

**Comment by iccicci** [comment]
> I just added a commit to get `nix build` to work correctly, by overriding the installPhase of the `production-deps` derivation.

Thank you @tshaynik !

@gytis-ivaskevicius , is this last introduced change enough to merge this PR?

Thank you

**Review by rhyslbw — CHANGES_REQUESTED** [review]
Just missing the `build:` prefix on c3ababdaa420448edc083c6ab1c6fc9cf43840a1

**Review by rhyslbw — APPROVED** [review]

**Pull request merged**
