### PR TITLE
New live mainnet eu central 1

### PR DESCRIPTION
**Pull request by gytis-ivaskevicius**
# Context

Changes:
- [Cherry-picked commit](https://github.com/input-output-hk/cardano-js-sdk/pull/1235) which configures pg-boss-worker properly
- Added new live-mainnet@eu-central-1 deployment  (Not currently live until everything syncs. Current domain is tmp-live-mainnet.lw.iog.io)

@iccicci Are we okay with deploying pg-boss change to all environments?

### CODE REVIEW

**Comment by iccicci** [comment]
The `pool-delist-schedule` also needs the `schedules.json` file and the path where it can be found through environment variable.

Was these two more changes imported in this branch by some other PR?

**Comment by iccicci** [comment]
> Are we okay with deploying pg-boss change to all environments?

I would do that not all at once: I would prefer to deploy it on `dev-preview`, check if it works as expected, proceed with `dev-preprod`... and so on.

**Comment by gytis-ivaskevicius** [comment]
Sorry, I should have mentioned that the way we sync it will not impact existing environments. What we do is:
- Create database `stakepoolv2`
- Spin up separate stakepool projector and pg-boss-worker on the new database
- Wait for it to sync
- Once it does, we switch providers to use new database
- Test it on dev
- If it works, push it to prod

@iccicci does this action plan sound good?

**Comment by iccicci** [comment]
To make this plan to work we need two `pg-boss-worker` and `stake-pool-projector` instances:

- a `pg-boss-worker`, `stake-pool-projector` and `stake-pool-provider` instances with old configuration pointing to the existing database
- a `pg-boss-worker` and `stake-pool-projector` instances with new configuration pointing to the new database

once synced, point the `stake-pool-provider` to the new database and dismiss old `pg-boss-worker` and `stake-pool-projector` instances and old database.

Do you confirm this is the plan?

**Comment by gytis-ivaskevicius** [comment]
Yes, I confirm

**Comment by iccicci** [comment]
> Yes, I confirm

Ok! Let's proceed

**Review by bernokl — APPROVED** [review]

**Pull request merged**
