### PR TITLE
Refactor/consolidate in-memory-key-manager with wallet

### PR DESCRIPTION
**Pull request by rhyslbw**
# Context
There's no practical benefit of keeping the `InMemoryKeyManager` separate from the wallet, in the same way
a particular hardware wallet would have, as most wallets will use the in-memory key manager
as the default.

# Proposed Solution
- Consolidate the `in-memory-key-manager` package with `wallet`.
# Important Changes Introduced
- Restructures the tests to reflect the source structure, removing source path mapping.
- https://github.com/input-output-hk/cardano-js-sdk/pull/102/commits/955079143cbd564e3e1452b39a6a73c371f16bd2

### CODE REVIEW

**Review by mkazlauskas — APPROVED** [review]
Looks good

**Comment by rhyslbw** [comment]
> Looks good. The tests are probably failing because it's missing a dependency: `"bip39": "^3.0.4"`

Yep, missed the failure since my local state had the package installed.

**Comment by rhyslbw** [comment]
Additional important change listed above @mkazlauskas

**Review by mkazlauskas — DISMISSED** [review]

**Comment by mkazlauskas** [comment]
> Additional important change listed above @mkazlauskas

Is CSL not following semantic versioning? Either way I think it's ok to pin to specific CSL version because cardano-js-sdk users are supposed to get CSL indirectly anyway.

**Comment by rhyslbw** [comment]
> Is CSL not following semantic versioning? Either way I think it's ok to pin to specific CSL version because cardano-js-sdk users are supposed to get CSL indirectly anyway.

I'm not sure, but given the critical nature of this dep, I'd prefer we lock it and remove the chance of unexpected changes.

**Review by mkazlauskas — APPROVED** [review]

**Pull request merged**
