### PR TITLE
fix(wallet): remove assets no longer available in total balance

### PR DESCRIPTION
**Pull request by mirceahasegan**
# Context

`SingleAddressWallet.assets$` not removing assets when they're no longer available in `balance$`

# Proposed Solution
Remove no longer available assets.

### CODE REVIEW

**Comment by mirceahasegan** [comment]
I trying a different approach as this one seems a bit messy

**Review by mkazlauskas — DISMISSED** [review]
Sourcing ` balanceAssetIds$` twice feels a little odd but looks good enough for me. If you can find a cleaner solution - great, otherwise I'm happy with this as-is.

**Comment by mirceahasegan** [comment]
I have added an alternate solution that comes with the following benefits:
- Does not subscribe twice to balanceTracker
- Does not verify the emitted map for equality thanks to it not repeating balanceTracker emitted values
- balanceTracker updates are emitted after metadata was fetched for all assets instead of fetching one by one and emitting incremental Map objects
- Does not 'remove', instead it rebuilds the map using only the assetIds from balance, with the asset info from the cached assets result

**Review by mkazlauskas — APPROVED** [review]
Well done! :tada:

**Comment by mirceahasegan** [comment]
I have rebased on master and squashed the changes.

**Review by mkazlauskas — APPROVED** [review]

**Review by rhyslbw — APPROVED** [review]
Great work @mirceahasegan 💪

**Pull request merged**
