### PR TITLE
chore: enable dev-mainnet asset provider

### PR DESCRIPTION
**Pull request by bernokl**
# Context

Enable asset-provider on dev-mainnewt. Disable asset on monolith

### CODE REVIEW

**Review by iccicci — APPROVED** [review]
LGTM!

**Review by gytis-ivaskevicius — CHANGES_REQUESTED** [review]
Please either keep asset provider on monolithic backend or enable provider everywhere

Leaving it enabled is fine, it's not going to get hit anyway

**Comment by iccicci** [comment]
> Please either keep asset provider on monolithic backend or enable provider everywhere
> 
> Leaving it enabled is fine, it's not going to get hit anyway

Nice catch! Yes, please enable `asset-provider` everywhere.

**Comment by bernokl** [comment]
@iccicci is this PR still relevant? or can I close it?

**Pull request closed without merging**
