### PR TITLE
chore: Docker Compose config fixes

### PR DESCRIPTION
**Pull request by rhyslbw**
# Context
This is a change to support cardano-db-sync@13, but it was missed or lost in the process of
upgrading. The snapshot expects this new path, otherwise, it will fail during unpacking. This change will only cause existing containers to be rebuilt, which will happen next time the stack is started without intervention. There were also a couple of other issues that I've corrected, see the commit log for details.

### CODE REVIEW

**Review by iccicci — APPROVED** [review]
I trust you. I take this more as an info than as review request. Thank you.

**Review by IvayloAndonov — APPROVED** [review]

**Comment by iccicci** [comment]
Sorry @rhyslbw ; I saw that only now.

Why an empty `docker-compose.yml` file in the root? Is it a refuse or is there a specific reason?

Thank you.

**Comment by rhyslbw** [comment]
Sorry reviewers, I pulled the trigger on requests too early. Updated the description, but please see each commit for details

**Review by mkazlauskas — APPROVED** [review]
LGTM

**Pull request merged**
