### PR TITLE
Flakify

### PR DESCRIPTION
**Pull request by jonringer**
# Context

Attempt to package this with nix.

depends on #256

To build the cardano services cli run `nix build .#@cardano-sdk/cardano-services` from in the repo.

### CODE REVIEW

**Comment by mkazlauskas** [comment]
@jonringer could you please drop a19aa4615ed9143ac172994c5415e31649b49c88 and rebase on master once #256 is merged? If we still need to list the packages after that, we might want to have 2 separate lists: 1 for library packages and 1 for cardano-services

**Comment by mkazlauskas** [comment]
@jonringer could you please drop a19aa4615ed9143ac172994c5415e31649b49c88 and rebase on master once #256 is merged? If we still need to list the packages after that, we might want to have 2 separate lists: 1 for library packages and 1 for cardano-services

**Comment by nrdxp** [comment]
@mkazlauskas, Ringer recently left the company but I'll take over from here. I just pushed a fix that mostly get's the package building, but I don't know how to get all the components to build together into a single package yet. The `mkYarnWorkspace` function doesn't seem to export a combined package.

**Comment by mkazlauskas** [comment]
@nrdxp need to rebase this on master, `cardano-services` build output directory has changed to `dist/cjs`

**Comment by mkazlauskas** [comment]
Can we close this in favor of #302 ?

**Pull request closed without merging**
