### PR TITLE
lw-7089: fix trezor transaction mismatching issue

### PR DESCRIPTION
**Pull request by tomislavhoracek**
# Context

This PR introduces a fix for the Trezor transaction hash mismatching issue

# Proposed Solution
The Trezor transaction hash must always match the one originating from Cardano JS SDK, otherwise transaction submission will fail.

# Important Changes Introduced
- No breaking changes

### CODE REVIEW

**Review by DominikGuzei — APPROVED** [review]
Nice work 🎉 so the problem was just bad test code?

**Comment by tomislavhoracek** [comment]
> Nice work 🎉 so the problem was just bad test code?

yeah :(

**Comment by tomislavhoracek** [comment]
@DominikGuzei @AngelCastilloB Can you check the last commit [d045670](https://github.com/input-output-hk/cardano-js-sdk/pull/880/commits/d045670ed2eb5eee8efa1acaf97823ebb7676922) please? 🙏

**Review by marcin-mazurek — APPROVED** [review]

**Review by DominikGuzei — APPROVED** [review]
still LGTM 👍

**Review by mkazlauskas — APPROVED** [review]

**Pull request merged**
