### PR TITLE
Feat/LW-8515 CIP95 replace getActivePublicStakeKeys with getRegistered getUnregisteredPubStakeKeys

### PR DESCRIPTION
**Pull request by mirceahasegan**
# Context

CIP-95 is still changing.
Adapting to the latest change regarding the new methods `getRegisteredPubStakeKeys`/`getUnregisteredPubStakeKeys`

# Proposed Solution
- cip95 add the new methods
- add the dapp-cip95 which uses the new methods
- add e2e web-extension tests for the new methods
- add e2e web-extension tests for CIP30 extensions api: `supportedExtensions`/`getExtensions`

# Important Changes Introduced

### CODE REVIEW

**Comment by mirceahasegan** [comment]
Update `[test(e2e): update cip-95 dapp](https://github.com/input-output-hk/cardano-js-sdk/pull/922/commits/373b0d8e259d642cc42291f08321e38f49ba307c)` commit message to: https://github.com/Ryun1/cip95-cardano-wallet-connector @3cda1ff9fb54deafe419419810622a2acc8ed578 (branch 1.5.0)

**Review by rhyslbw — APPROVED** [review]
Looks great @mirceahasegan, well done :rocket: 

It seems like there's some commits that can be squash. Consider squashing d7f0dcc455144e64c62ebf5490a91018a2820add with de21450665216fa02c1ffa8a0ff3350f0d3949c1 if the web extension tests fail without the latter commit. Also 7d96b053c40b5b771ce9c69e530041bbf0d3a7ec looks like the same atomic change

**Review by mkazlauskas — APPROVED** [review]
Great work! :rocket:

**Comment by mirceahasegan** [comment]
> Also [7d96b05](https://github.com/input-output-hk/cardano-js-sdk/commit/7d96b053c40b5b771ce9c69e530041bbf0d3a7ec) looks like part of the atomic change
This commit adds tests for a previous PR. I would prefer keeping it separate.

**Comment by rhyslbw** [comment]
> This commit adds tests for a previous PR. I would prefer keeping it separate.

On that basis, well done in the scoping 🦾

**Pull request merged**
