### PR TITLE
fix: typeorm asset provider release query runner once

### PR DESCRIPTION
**Pull request by mkazlauskas**
# Context

Attempting to release again throws an error

query-runner-released

it should be released in scope where it's created

# Proposed Solution

# Important Changes Introduced

### CODE REVIEW

**Review by iccicci — DISMISSED** [review]
LGTM!

**Review by mirceahasegan — DISMISSED** [review]
good catch @mkazlauskas 🕵️

**Review by mirceahasegan — APPROVED** [review]
nice refactoring! 🥇

**Review by iccicci — APPROVED** [review]
GJ!

**Pull request merged**
